### ISSUE TITLE
[BUG] Brand Guide URL 404s

### ISSUE THREAD

**Issue by wifelette** [ember-learn/ember-website#1051]
**Describe the bug**
On `/logos` aka `/branding`, there is a link to the PDF brand guide. It goes to `https://emberjs.com/pdfs/Ember-Brand-Guidelines.pdf/` instead of `https://emberjs.com/pdfs/Ember-Brand-Guidelines.pdf`. The trailing slash produces a 404 instead of the Guide, which is otherwise there and working.

<img width="477" alt="image" src="https://github.com/ember-learn/ember-website/assets/25433/456972a4-ff1f-42c2-a10b-35b0f4f57488">

**To Reproduce**
1. Go to `https://emberjs.com/logos/`
2. Click on Download Brand Guidelines

**Comment by anshikjain18** [comment]
Hello @wifelette, I would like to work on this issue. From what I can see opening the 'Download brand guidelines (PDF)' link in a new tab works fine but if we try to open it in the same tab it gives 404. We can set the anchor tag to always open the link in a new tab so that the branding page is still present when we click the link. This solution is recommended but if the requirements are to open the link in the same tab that can also be done.

**Comment by wifelette** [comment]
That sounds great to me! So long as we aren't 404ing anymore :) That said, happy for anyone else on the Learning Team with more current/specific technical thoughts to jump in. Whatever gets the job done, and thanks for stepping up to help!

**Comment by rameshvoodi** [comment]
hello @wifelette I have made a PR ##1052 that can solve this issue, please look into it.
