### ISSUE TITLE
Page not rendering with node@6.x version

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/ember-website#178]
While running node@6 and `ember serve`, the page doesn't load but throws an error under controllers/application.js `replaceLinks()` method where there is a usage of the spread operator. The same works if `?fastboot=false` is used.

Documentation should include running this project from node@8.?

**Comment by locks** [comment]
This is already specified in the project's [`package.json`](https://github.com/ember-learn/ember-website/blob/master/package.json#L74-L76). Your node's version may be too old to show the proper warning, can you confirm it doesn't complain?

**Comment by mansona** [comment]
@abhilashlr I'm afraid @locks is right with this one, it does require a minimum of node v8.x mainly because we rely very heavily on [prember](https://github.com/ef4/prember) which also requires a minimum of node v8.x 

I don't know if we should put this in the current readme because as @locks says it does state it in the package.json 🤔 are there any warnings when you try to run it? 

I'm going to close this issue but we can continue to discuss if we feel like it 😄

**Comment by abhilashlr** [comment]
No @mansona @locks , there seems to be no error/warning while running `ember serve` command.
