### ISSUE TITLE
Handle dates in /releases so they aren't always wrong

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-website#261]
This site is perpetually out of date because everything is hard coded.

This app should be data-driven for confirmed past dates, such as "latest minor release". Forward looking dates should be removed because they are not able to be extrapolated from data.

It's a hack, but the `versions.json` used by the API docs would probably be ok to depend on.

**Comment by mansona** [comment]
this is very much related to https://github.com/ember-learn/ember-website/issues/164 and there are some ways that we can actually hit the npm api to get latest release data live 🎉

**Comment by mansona** [comment]
I think this is still valid 👍

**Comment by cincodenada** [comment]
I came here because /releases is currently showing 3.27b3 as current, with 3.27 "Coming the week of May 3", when as of this writing the current release is 3.27.5

Looking at the code it looks like there was some work to make this dynamic, the releases/index controller does a `this.model.find()` to find a beta release...but it seems like maybe it's returning the first beta release, although I don't know what "first" means because I don't know what order the `projects` model will return things in.

**Comment by ijlee2** [comment]
Hi, @cincodenada. Thank you for letting us know that the releases page(s) are out of date. I can update the information (done manually).
