### ISSUE TITLE
Update links from emberjs.com to `/release/` to avoid extra redirect

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-website#289]
Currently when you go to `/` on this app it automatically redirects you to `/release/` but if we have the power to update links we should link directly to release 💪

**Comment by jenweber** [comment]
https://github.com/ember-learn/ember-website/pull/290

**Comment by locks** [comment]
Sorry, I didn't notice there was a "closes x" in the commit itself, I only saw the updated PR description.

**Comment by mansona** [comment]
this is probably still an issue 👍

**Comment by locks** [comment]
Still relevant.

**Comment by locks** [comment]
@vinodhrajamuralidharan can you look into this one?

**Comment by alexeykostevich** [comment]
@vinodhrajamuralidharan has fixed all the links in the [ember-learn/ember-website](https://github.com/ember-learn/ember-website) repository within https://github.com/ember-learn/ember-website/pull/618.

To close this ticket, we also need to update links in the website header, which are defined in different repositories. Since the Ember website consists of many parts, there are many places where these URLs are mentioned.

Here is what I found:
1. [ember-styleguide](https://github.com/ember-learn/ember-styleguide/blob/f03492c4adc171daabea12d1d694f46ee1b47529/addon/constants/links.js#L5) repository defines links for the [Ember](https://emberjs.com), [Ember Guides](https://guides.emberjs.com) and [Ember CLI Guides](https://cli.emberjs.com) headers.
2. [ember-api-docs](https://github.com/ember-learn/ember-api-docs/blob/8e9acefee89b6ad02bd25c6829495719a9b1bac8/app/controllers/application.js#L10) repository defines links for the [Ember API Reference](https://api.emberjs.com) header.
3. [ember-blog](https://github.com/ember-learn/ember-blog/blob/6ba802ed0e575d57ca6774fba3059d9a4a1822dc/source/_header.html.erb#L18) repository defines links for the [Ember Blog](https://blog.emberjs.com/) header.

If I understand correctly, all the websites will be eventually updated to use [ember-styleguide](https://github.com/ember-learn/ember-styleguide), so it makes sense to fix URLs only there and let the fix propagate eventually to all other places.

@mansona please, let me know if you have any concerns with updating links in [ember-styleguide](https://github.com/ember-learn/ember-blog/blob/6ba802ed0e575d57ca6774fba3059d9a4a1822dc/source/_header.html.erb#L18-L20)? It might  be not the best place to apply routing optimizations (to remove the redirect) but definitely the simplest.

Alternatives will be:
1. Configure routing to make https://guides.emberjs.com and https://api.emberjs.com as the default routes for the latest release (probably, the best option if there are no technical challenges with this).
2. Keep everything as is and close the issue.
3. Add the `/release/` path to URLs on the application side (probably, the worst option).
