### ISSUE TITLE
[Question] Should the website now make use of SW to cache most of the static json requests?

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/ember-website#604]
Most of the static JSON (with loading times in brackets) like
1. team-members/all.json (~350ms)
2. tomsters/all.json (~500ms)
3. users/all.json (~750ms)
4. sponsors/all.json (~350ms)
5. meetups/all.json (~400ms)
6. showcases/all.json (~350ms)

These could be cached and may not require requests from being fired.

Thoughts?

**Comment by locks** [comment]
We need to fingerprint them in that case, so we can invalidate them when they are updated!

**Comment by mansona** [comment]
I don't know the value of using a SW for the website 🤔 I know it would add a few more points to our Lighthouse score but I (personally) don't think it's worth the **significantly** higher complexity. And there is always the added risk that we might permanently break some people's experience with no way to undo it 🙈 

There are some other low-hanging fruit that we could do. We could just add some caching to each of the json files (maybe a day for them by default or something?) which might prevent people from having to load them too many times as they navigate around the site.

Also we could pre-load them on all landing pages so that people would have them pre-cached when navigating to a page that needs them, but I personally don't like this approach because it means that people would be forced to download something that they might never use and it could use up their data.

There is also another option: "do nothing". Right now none of these requests are blocking any initial loads of any pages (because that is how fastboot works) and they are only being downloaded when you navigate between pages. If we turned off the Ember "run time" application then the amount of data and time taken to download any of the pages in question would be more than the size of these JSON files so it's already quite efficient 😂 

I thought I would share my thoughts on it but feel free to ask any questions if I haven't explained anything enough 👍

**Comment by sivakumar-kailasam** [comment]
We could begin by leveraging the fastboot shoebox to rehydrate the data store so that the first page's json files don't need to be loaded as a part of the page's rehydration. [ember-data-fastboot](https://github.com/cardstack/ember-data-fastboot) & [ember-data-storefront](https://embermap.github.io/ember-data-storefront/docs/api/mixins/fastboot-adapter) have the ability to do this.

**Comment by mansona** [comment]
I would be interested in trying out ember-data-fastboot to see if it works 🎉 I see some issues where people are mentioning that it still makes the request because of background reloading or something 🤔 

I don't want us to move over to ember-data-storefront as I think it's important that we use the default `ember-data` on our main website 👍

**Comment by mansona** [comment]
and when I say "would be interested" I really mean PRs welcome 😂 also we need to probably experiment with actual Fastboot Rehydration and make sure that any shoebox stuff we do doesn't break that 👍
