### ISSUE TITLE
Subroute support for survey

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/ember-website#832]
This [issue](https://github.com/ember-learn/ember-website/issues/765) was partially addressed, but there still seems to be an open question about whether we want to provide subroutes support.

cc: @mansona

**Comment by ijlee2** [comment]
@jaredgalanis I believe we (@MelSumner and I) do want to support subdomains (subroutes).

I think updating URLs for existing survey result pages isn't urgent, and would like to suggest that we wait working on it until #796, #826, and a code-cleanup issue are done.

The 2021 survey results page, when ready, can use a subdomain immediately. For example, `/survey/results-2021`.

**Comment by mansona** [comment]
So we're actually talking about **subroutes** here? I wan't to be as clear as possible in this issue because subdomains would imply something like https://survey.emberjs.com or https://2019.emberjs.com which I'm assuming we're not actually talking about @ijlee2 based on your response

If we're talking about Sub-routes then we should not use subdomain anywhere in the description of this issue (or comments) so that we don't confuse people 👍

**Comment by ijlee2** [comment]
Ah, good point. Yep, I was thinking of subroutes.

**Comment by mansona** [comment]
Perfect! thanks for the clarification @ijlee2 🎉

**Comment by ijlee2** [comment]
The survey result pages have been refactored. We can now ask the public to help out with adding subroutes for each year.

**Comment by takshch** [comment]
Is this issue is fixed or can I take this issue!

**Comment by ijlee2** [comment]
@takshch Hello, the issue is still open. I will assign it to you.
